################# nacos配置文件 #################
server:
  port: 8081

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: common-upms
        uri: lb://common-upms
        predicates:
        - Path=/admin/upms/**
        filters:
        - StripPrefix=2
        - name: Hystrix
          args:
            name: default
            fallbackUri: forward:/fallback
      - id: common-online
        uri: lb://common-online
        predicates:
          - Path=/admin/online/**
        filters:
          - StripPrefix=1
          - name: Hystrix
            args:
              name: default
              fallbackUri: forward:/fallback
      - id: common-flow
          uri: lb://common-flow
          predicates:
            - Path=/admin/flow/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/fallback

redis:
  # redisson的配置。每个服务可以自己的配置文件中覆盖此选项。
  redisson:
    # 如果该值为false，系统将不会创建RedissionClient的bean。
    enabled: true
    # mode的可用值为，single/cluster/sentinel/master-slave
    mode: single
    # single: 单机模式
    #   address: redis://localhost:6379
    # cluster: 集群模式
    #   每个节点逗号分隔，同时每个节点前必须以redis://开头。
    #   address: redis://localhost:6379,redis://localhost:6378,...
    # sentinel:
    #   每个节点逗号分隔，同时每个节点前必须以redis://开头。
    #   address: redis://localhost:6379,redis://localhost:6378,...
    # master-slave:
    #   每个节点逗号分隔，第一个为主节点，其余为从节点。同时每个节点前必须以redis://开头。
    #   address: redis://localhost:6379,redis://localhost:6378,...
    address: redis://localhost:6379
    # 链接超时，单位毫秒。
    timeout: 60000
    # 单位毫秒。分布式锁的超时检测时长。
    # 如果一次锁内操作超该毫秒数，或在释放锁之前异常退出，Redis会在该时长之后主动删除该锁使用的key。
    lockWatchdogTimeout: 60000
    # redis 密码，空可以不填。
    password:
    pool:
      # 连接池数量。
      poolSize: 20
      # 连接池中最小空闲数量。
      minIdle: 5

# 配置ribbon超时时间
ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 20000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            # 超过此时间后进入熔断;这个时间应该大于后端及其ribbon的时间;否则后端接口未执行完就进入熔断
            timeoutInMilliseconds: 50000

bluetron-nb-common:
  application:
    # Jwt令牌加密的签名值。该值的长度要超过10个字符(过短会报错)。
    tokenSigningKey: Common-signing-key
    # Jwt令牌在Http Header中的键名称。
    tokenHeaderKey: Authorization
    # Jwt令牌刷新后在Http Header中的键名称。
    refreshedTokenHeaderKey: RefreshedToken
    # Jwt令牌过期时间(毫秒)。
    expiration: 72000000
    # 跨域的IP(http://192.168.10.10:8086)白名单列表，多个IP之间逗号分隔(* 表示全部信任，空白表示禁用跨域信任)。
    credentialIpList: "*"
    # Session会话和用户权限在Redis中的过期时间(秒)。
    sessionExpiredSeconds: 86400